
osx_image: xcode10
language: objective-c
script:
- xcodebuild test -workspace Example/PixelTest.xcworkspace -scheme PixelTest-Example -sdk iphonesimulator12.0 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' ONLY_ACTIVE_ARCH=NO | xcpretty
